#! /bin/bash
#External rule that always splits the biggest window of the desktop
bwid=$(bspc query -W -w biggest.tiled)
wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")
# only do something if there's already a tiled window on this desktop
if [ -n "$(bspc query -W -w biggest.tiled)" ]; then
    if [ -n "$(bspc query -W -w biggest.tiled.manual)" ]; then
        # we have a presel: use it by choosing the 'target' window
        echo window=biggest.tiled.manual
    else
        # no presel exists: transplant into the biggest window
        wattr wh $bwid | {
			read width height
			if [ $width -gt $height ] ; then
				echo "window=biggest.tiled split_dir=left"
			else
				echo "window=biggest.tiled split_dir=down"
			fi
#			echo "split_ratio=0.5"
		}	
    fi
fi
