#!/bin/bash

##Make sure only one instance of autogap is run
if ! mkdir /tmp/autogap.lock; then
    printf "Failed to aquire lock.\n" >&2
    exit 1
fi
trap 'rm -rf /tmp/autogap.lock' EXIT  # remove the lockdir on exit


bspc control --subscribe | while read line; do
  W=$(bspc query --desktop focused --windows | wc -l)
  G=$(echo "51 - ($W - 1) * 10" | bc)
  [[ $G -lt 1 ]] && G=1
    bspc config --desktop focused window_gap $G
done


