#!/bin/bash
#
# 
#
###
if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc

eval $(xdotool getmouselocation --shell)
menu_widht=200
monitor_widht=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
monitor_height=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
lines=14
menu_height=$(echo "$lines * 23" | bc)
maxx=$(echo "$monitor_widht - $menu_widht" | bc)
miny=$PANEL_HEIGHT
maxy=$(echo "$monitor_height - $menu_height" | bc)
XP=$X
[[ $XP -gt $maxx ]] && XP=$maxx
YP=$Y
[[ $YP -lt $miny ]] && YP=$miny
[[ $YP -gt $maxy ]] && YP=$maxy

#DMENU='dmenu -i -l 5 -y 30 -x 1720 -w 200 -fn sans11 -nb '#000000' -nf '#99CC99' -sb '#99CC99' -sf '#000000''
#DMENU='dmenu $DMENU_OPTIONS'
choice=$(echo -e "Run\nTerminal\nFiles\nBrowser\nEditor\nPackageManager\nKeybinds" | dmenu -i -fn sans11 -l $lines -y $YP -x $XP -w $menu_widht -nb '#000000' -nf '#99CC99' -sb '#99CC99' -sf '#000000')

case "$choice" in
  Run) dboxrun & ;;
  Terminal) terminal & ;;
  Files) xdg-open ~ & ;;
  Browser) xdg-open https://manjaro.github.io/ & ;;
  Editor) gedit || medit || leafpad || geany || mousepad || kate & ;;
  PackageManager) terminal -e yaourt-gui & ;;
  Keybinds) terminal -e nano .config/sxhkd/sxhkdrc & ;;
esac
