#!/bin/bash

#First, configure stuff with xrandr
USER=$(who | grep :0\) | cut -f 1 -d ' ')
export DISPLAY=:0.0
export XAUTHORITY=/home/$USER/.Xauthority

default_screen=$(bspc query -M | awk NR==1)
function connect_VGA(){
xrandr --output VGA1 --auto --left-of $default_screen
}

function disconnect_VGA(){
xrandr --output VGA1 --off
}

function connect_DP(){
xrandr --output DP1 --auto --left-of $default_screen
}

function disconnect_DP(){
xrandr --output DP1 --off
}

function connect_LVDS(){
xrandr --output LVDS1 --auto --left-of $default_screen
}

function disconnect_LVDS(){
xrandr --output LVDS1 --off
}

function connect_HDMI(){
xrandr --output HDMI1 --auto --left-of $default_screen
}

function disconnect_HDMI(){
xrandr --output HDMI1 --off
}
xrandr | grep "VGA1 connected" &> /dev/null && connect_VGA || disconnect_VGA
xrandr | grep "HDMI1 connected" &> /dev/null && connect_HDMI || disconnect_HDMI
xrandr | grep "DP1 connected" &> /dev/null && connect_DP || disconnect_DP
xrandr | grep "LVDS1 connected" &> /dev/null && connect_LVDS || disconnect_LVDS

#Then, create workspaces on all monitors
  I=1
  M=$(bspc query -M | wc -l)
  if [[ "$M" == 1 ]]; then
    bspc monitor -d I II III IV V
  elif [[ "$M" == 2 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III IV V
     bspc monitor $(bspc query -M | awk NR==2) -d VI VII VIII IX X
  elif [[ "$M" == 3 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III IV
     bspc monitor $(bspc query -M | awk NR==2) -d V VI VII
     bspc monitor $(bspc query -M | awk NR==3) -d VIII IX X
  elif [[ "$M" == 4 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III
     bspc monitor $(bspc query -M | awk NR==2) -d IV V VI
     bspc monitor $(bspc query -M | awk NR==3) -d VII VIII
     bspc monitor $(bspc query -M | awk NR==4) -d IX X
  elif [[ "$M" == 5 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II
     bspc monitor $(bspc query -M | awk NR==2) -d III IV
     bspc monitor $(bspc query -M | awk NR==3) -d V VI
     bspc monitor $(bspc query -M | awk NR==4) -d VII VIII
     bspc monitor $(bspc query -M | awk NR==5) -d IX X
  else
    for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$I" \
        -d $I/{a,b,c}
     let I++
     done
  fi


