#!/bin/bash

#bspc control --subscribe | while read line; do
  I=1
  M=$(bspc query -M | wc -l)
  if [[ "$M" == 1 ]]; then
    bspc monitor -d I II III IV V
  elif [[ "$M" == 2 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III IV V
     bspc monitor $(bspc query -M | awk NR==2) -d VI VII VIII IX X
  elif [[ "$M" == 3 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III IV
     bspc monitor $(bspc query -M | awk NR==2) -d V VI VII
     bspc monitor $(bspc query -M | awk NR==3) -d VIII IX X
  elif [[ "$M" == 4 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II III
     bspc monitor $(bspc query -M | awk NR==2) -d IV V VI
     bspc monitor $(bspc query -M | awk NR==3) -d VII VIII
     bspc monitor $(bspc query -M | awk NR==4) -d IX X
  elif [[ "$M" == 5 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d I II
     bspc monitor $(bspc query -M | awk NR==2) -d III IV
     bspc monitor $(bspc query -M | awk NR==3) -d V VI
     bspc monitor $(bspc query -M | awk NR==4) -d VII VIII
     bspc monitor $(bspc query -M | awk NR==5) -d IX X
  else
    for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$I" \
        -d $I/{a,b,c}
     let I++
     done
  fi


